version: '2'
services:
  elasticsearch:
    build: ./elasticsearch
    image: elk/elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  logstash:
    build: ./logstash
    image: elk/logstash
    command: logstash -f /etc/logstash/conf.d/logstash.conf -v --debug --verbose
    volumes:
      - '/$HOME/Disks/wiamlogs:/data'
    ports:
      - "5000:5000"
      - "5514:5514"
    links:
      - elasticsearch
  kibana:
    build: ./kibana
    image: elk/kibana
    ports:
      - "5601:5601"
    links:
      - elasticsearch
volumes:
  elasticsearch-data:
    driver: local